#!/usr/bin/env bash

# Install Nginx web server
sudo apt-get update
sudo apt-get install -y nginx

# Configure Nginx to redirect /redirect_me
sudo rm /etc/nginx/sites-enabled/default
sudo tee /etc/nginx/sites-available/redirect_me <<EOF
server {
    listen 80;
    server_name example.com;

    location /redirect_me {
        return 301 https://www.example.com/new_page;
    }
}
EOF
sudo ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/redirect_me

# Restart Nginx
sudo service nginx restart
