#!/usr/bin/env bash

# Install Nginx web server
sudo apt-get update
sudo apt-get install -y nginx

# Create a custom 404 error page
sudo tee /usr/share/nginx/html/404.html <<EOF
<!DOCTYPE html>
<html>
<head>
    <title>404 Not Found</title>
</head>
<body>
    <h1>404 Not Found</h1>
    <p>Ceci n'est pas une page.</p>
</body>
</html>
EOF

# Update Nginx configuration to use the custom 404 page
sudo sed -i 's|#error_page 404 /404.html;|error_page 404 /404.html;|g' /etc/nginx/sites-enabled/default

# Restart Nginx
sudo service nginx restart
